# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Code Craft 
email: prashanth.moorthy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codecraft.blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codecraftblog 
github_username: codecraftblog 

# Build settings
markdown: kramdown
#theme: minima
remote_theme: "mmistakes/so-simple-theme@3.2.0"

plugins:
  - jekyll-feed

#skin: "/assets/css/skins/dark.css"
#skin: "/assets/css/skins/default.css"
#skin: "/assets/css/skins/prashdefault.css"
#skin: "/assets/css/skins/light.css"
#skin: "/assets/css/skins/dark.css"
skin: "/assets/css/skins/prashcustom.css"

author:
  name: Prashanth 
  twitter: codecraftblog 
  picture: /images/profileImage_150X150.png

read_time: true
words_per_minute: 200
#page_excerpts: true

google_analytics: UA-156605848-2 

footer_links:
  - title: Twitter
    url: https://twitter.com/codecraftblog
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/TheAppMentor 
    icon: fab fa-github-square

copyright: "@codecraftblog"

excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-cayman
